#!/bin/bash

#TODO move this stuff in to Build.hs
#TODO versions
#TODO `--force-reinstalls` isn't what we want - better to just delete the old env file
cabal install --force-reinstalls --package-env . --lib \
    aeson \
    aeson-pretty \
    ansi-terminal \
    async \
    base \
    bytestring \
    Chart \
    Chart-diagrams \
    colour \
    comonad \
    composition \
    containers \
    dhall \
    diagrams-core \
    diagrams-lib \
    diagrams-svg \
    directory \
    evdev \
    evdev-streamly \
    extra \
    filepath \
    filepath-bytestring \
    freer-simple \
    generic-optics \
    ghc \
    graphviz \
    hashable \
    hashtables \
    hinotify \
    http-client \
    http-client-tls \
    JuicyPixels \
    lens \
    lifx-lan \
    lucid \
    monad-loops \
    mtl \
    mwc-random \
    network \
    network-uri \
    optics \
    optparse-applicative \
    optparse-generic \
    parsec \
    pretty-simple \
    prettyprinter \
    prettyprinter-graphviz \
    prettyprinter-lucid \
    process \
    random \
    raw-strings-qq \
    rawfilepath \
    safe \
    sbv \
    scientific \
    shake \
    split \
    stm \
    streamly \
    streams \
    text \
    time \
    transformers \
    uniplate \
    unix \
    unordered-containers \
    vector \
    vector-algorithms \
    X11 \
    yaml \
